// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbS_bBcTroT-BYwUJ0kT2iNn9NkcytE8',
    appId: '1:589958621003:web:d44a3af6d677f0d29f6ace',
    messagingSenderId: '589958621003',
    projectId: 'eduzon-7c23d',
    authDomain: 'eduzon-7c23d.firebaseapp.com',
    storageBucket: 'eduzon-7c23d.firebasestorage.app',
    measurementId: 'G-850F7V7CZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_p7eefqg6eRuvAIpbjfl7JD9ETDFkpvE',
    appId: '1:589958621003:android:6808809f65a08a699f6ace',
    messagingSenderId: '589958621003',
    projectId: 'eduzon-7c23d',
    storageBucket: 'eduzon-7c23d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_8nWbakJ5qc56SC4eIDgN164a4I_TQI',
    appId: '1:589958621003:ios:5563cd397c8958219f6ace',
    messagingSenderId: '589958621003',
    projectId: 'eduzon-7c23d',
    storageBucket: 'eduzon-7c23d.firebasestorage.app',
    iosBundleId: 'com.example.eduzon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_8nWbakJ5qc56SC4eIDgN164a4I_TQI',
    appId: '1:589958621003:ios:5563cd397c8958219f6ace',
    messagingSenderId: '589958621003',
    projectId: 'eduzon-7c23d',
    storageBucket: 'eduzon-7c23d.firebasestorage.app',
    iosBundleId: 'com.example.eduzon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjbS_bBcTroT-BYwUJ0kT2iNn9NkcytE8',
    appId: '1:589958621003:web:ae8b6f8627f0321d9f6ace',
    messagingSenderId: '589958621003',
    projectId: 'eduzon-7c23d',
    authDomain: 'eduzon-7c23d.firebaseapp.com',
    storageBucket: 'eduzon-7c23d.firebasestorage.app',
    measurementId: 'G-6VY7EVHYXD',
  );
}
